[client]
showErrorDetails = true

[server]
headless = true

[logger]
level = "error"

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#F5F5F5"
secondaryBackgroundColor = "#E9ECEF"
textColor = "#262730"
font = "sans serif"
